# Taking care of missing data

In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
import warnings
warnings.filterwarnings('ignore')
from sklearn import preprocessing

In [2]:
os.chdir("C:/Users/P NIVAS/Desktop/Remote Internship-2020/Datasets")
os.getcwd()
data= pd.read_csv('cereal.csv')
data

name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0     5.0       6     280        25      3     1.0  0.33  68.402973  
1     8.0       8     135         0      3     1.0  1.00  33.983679  
2     7.0       5     320        25      3     1.0  0.33  59.425505  
3     8.0       0     330        25      3     1.0  0.50  93.704912  
4    14.0       8      -1        25      3     1.0  0.75  34.384843  
..    ...     ...     ...       ...    ...     ...   ...        ...  
72   21.0       3      60        25      3     1.0  0.75  39.106174  
73   13.0      12      25        25      2     1.0  1.00  27.753301  
74   17.0       3     115        25      1     1.0  0.67  49.787445  
75   17.0       3     110        25      1     1.0  1.00  51.592193  
76   16.0       8      60        25      1     1.0  0.75  36.187559  

[77 rows x 16 columns]

In [3]:
data.isnull()

name    mfr   type  calories  protein    fat  sodium  fiber  carbo  \
0   False  False  False     False    False  False   False  False  False   
1   False  False  False     False    False  False   False  False  False   
2   False  False  False     False    False  False   False  False  False   
3   False  False  False     False    False  False   False  False  False   
4   False  False  False     False    False  False   False  False  False   
..    ...    ...    ...       ...      ...    ...     ...    ...    ...   
72  False  False  False     False    False  False   False  False  False   
73  False  False  False     False    False  False   False  False  False   
74  False  False  False     False    False  False   False  False  False   
75  False  False  False     False    False  False   False  False  False   
76  False  False  False     False    False  False   False  False  False   

    sugars  potass  vitamins  shelf  weight   cups  rating  
0    False   False     False  False   False  False   False  
1    False   False     False  False   False  False   False  
2    False   False     False  False   False  False   False  
3    False   False     False  False   False  False   False  
4    False   False     False  False   False  False   False  
..     ...     ...       ...    ...     ...    ...     ...  
72   False   False     False  False   False  False   False  
73   False   False     False  False   False  False   False  
74   False   False     False  False   False  False   False  
75   False   False     False  False   False  False   False  
76   False   False     False  False   False  False   False  

[77 rows x 16 columns]

In [4]:
data.apply(lambda x: sum(x.isnull()),axis=0)

name        0
mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       0
sugars      0
potass      0
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

In [5]:
#from the above output, we can concluded that there are no none values, but we cannot say that there are no missing values

In [6]:
data.apply(lambda x: sum(x==0),axis=0)

name         0
mfr          0
type         0
calories     0
protein      0
fat         27
sodium       9
fiber       19
carbo        0
sugars       7
potass       0
vitamins     8
shelf        0
weight       0
cups         0
rating       0
dtype: int64

In [7]:
#there are some missing values, let's  replace them

In [8]:
data.columns = data.columns.str.strip() 

In [9]:
data['fat'].replace(0,np.NaN,inplace=True)
data['sodium'].replace(0,np.NaN,inplace=True)
data['fiber'].replace(0,np.NaN,inplace=True)
data['sugars'].replace(0,np.NaN,inplace=True)
data['vitamins'].replace(0,np.NaN,inplace=True)
data

name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4  1.0   130.0   10.0   
1           100% Natural Bran   Q    C       120        3  5.0    15.0    2.0   
2                    All-Bran   K    C        70        4  1.0   260.0    9.0   
3   All-Bran with Extra Fiber   K    C        50        4  NaN   140.0   14.0   
4              Almond Delight   R    C       110        2  2.0   200.0    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2  1.0   250.0    NaN   
73                       Trix   G    C       110        1  1.0   140.0    NaN   
74                 Wheat Chex   R    C       100        3  1.0   230.0    3.0   
75                   Wheaties   G    C       100        3  1.0   200.0    3.0   
76        Wheaties Honey Gold   G    C       110        2  1.0   200.0    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0     5.0     6.0     280      25.0      3     1.0  0.33  68.402973  
1     8.0     8.0     135       NaN      3     1.0  1.00  33.983679  
2     7.0     5.0     320      25.0      3     1.0  0.33  59.425505  
3     8.0     NaN     330      25.0      3     1.0  0.50  93.704912  
4    14.0     8.0      -1      25.0      3     1.0  0.75  34.384843  
..    ...     ...     ...       ...    ...     ...   ...        ...  
72   21.0     3.0      60      25.0      3     1.0  0.75  39.106174  
73   13.0    12.0      25      25.0      2     1.0  1.00  27.753301  
74   17.0     3.0     115      25.0      1     1.0  0.67  49.787445  
75   17.0     3.0     110      25.0      1     1.0  1.00  51.592193  
76   16.0     8.0      60      25.0      1     1.0  0.75  36.187559  

[77 rows x 16 columns]

In [10]:
data.apply(lambda x: sum(x.isnull()),axis=0)

name         0
mfr          0
type         0
calories     0
protein      0
fat         27
sodium       9
fiber       19
carbo        0
sugars       7
potass       0
vitamins     8
shelf        0
weight       0
cups         0
rating       0
dtype: int64

In [11]:
data['fat'].fillna(data['fat'].mean(), inplace=True)
data['sodium'].fillna(data['sodium'].mean(), inplace=True)
data['fiber'].fillna(data['fiber'].mean(), inplace=True)
data['sugars'].fillna(data['sugars'].mean(), inplace=True)
data['vitamins'].fillna(data['vitamins'].mean(), inplace=True)

In [12]:
data

name mfr type  calories  protein   fat  sodium  \
0                   100% Bran   N    C        70        4  1.00   130.0   
1           100% Natural Bran   Q    C       120        3  5.00    15.0   
2                    All-Bran   K    C        70        4  1.00   260.0   
3   All-Bran with Extra Fiber   K    C        50        4  1.56   140.0   
4              Almond Delight   R    C       110        2  2.00   200.0   
..                        ...  ..  ...       ...      ...   ...     ...   
72                    Triples   G    C       110        2  1.00   250.0   
73                       Trix   G    C       110        1  1.00   140.0   
74                 Wheat Chex   R    C       100        3  1.00   230.0   
75                   Wheaties   G    C       100        3  1.00   200.0   
76        Wheaties Honey Gold   G    C       110        2  1.00   200.0   

        fiber  carbo     sugars  potass   vitamins  shelf  weight  cups  \
0   10.000000    5.0   6.000000     280  25.000000      3     1.0  0.33   
1    2.000000    8.0   8.000000     135  31.521739      3     1.0  1.00   
2    9.000000    7.0   5.000000     320  25.000000      3     1.0  0.33   
3   14.000000    8.0   7.614286     330  25.000000      3     1.0  0.50   
4    1.000000   14.0   8.000000      -1  25.000000      3     1.0  0.75   
..        ...    ...        ...     ...        ...    ...     ...   ...   
72   2.856897   21.0   3.000000      60  25.000000      3     1.0  0.75   
73   2.856897   13.0  12.000000      25  25.000000      2     1.0  1.00   
74   3.000000   17.0   3.000000     115  25.000000      1     1.0  0.67   
75   3.000000   17.0   3.000000     110  25.000000      1     1.0  1.00   
76   1.000000   16.0   8.000000      60  25.000000      1     1.0  0.75   

       rating  
0   68.402973  
1   33.983679  
2   59.425505  
3   93.704912  
4   34.384843  
..        ...  
72  39.106174  
73  27.753301  
74  49.787445  
75  51.592193  
76  36.187559  

[77 rows x 16 columns]

In [13]:
data.apply(lambda x: sum(x.isnull()),axis=0)

name        0
mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       0
sugars      0
potass      0
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

# Label Encoding

In [14]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
lb2=LabelEncoder()
data['type']=lb.fit_transform(data['type'])
data['mfr']=lb.fit_transform(data['mfr'])
data['name']=lb.fit_transform(data['name'])
data

name  mfr  type  calories  protein   fat  sodium      fiber  carbo  \
0      0    3     0        70        4  1.00   130.0  10.000000    5.0   
1      1    5     0       120        3  5.00    15.0   2.000000    8.0   
2      2    2     0        70        4  1.00   260.0   9.000000    7.0   
3      3    2     0        50        4  1.56   140.0  14.000000    8.0   
4      4    6     0       110        2  2.00   200.0   1.000000   14.0   
..   ...  ...   ...       ...      ...   ...     ...        ...    ...   
72    72    1     0       110        2  1.00   250.0   2.856897   21.0   
73    73    1     0       110        1  1.00   140.0   2.856897   13.0   
74    74    6     0       100        3  1.00   230.0   3.000000   17.0   
75    75    1     0       100        3  1.00   200.0   3.000000   17.0   
76    76    1     0       110        2  1.00   200.0   1.000000   16.0   

       sugars  potass   vitamins  shelf  weight  cups     rating  
0    6.000000     280  25.000000      3     1.0  0.33  68.402973  
1    8.000000     135  31.521739      3     1.0  1.00  33.983679  
2    5.000000     320  25.000000      3     1.0  0.33  59.425505  
3    7.614286     330  25.000000      3     1.0  0.50  93.704912  
4    8.000000      -1  25.000000      3     1.0  0.75  34.384843  
..        ...     ...        ...    ...     ...   ...        ...  
72   3.000000      60  25.000000      3     1.0  0.75  39.106174  
73  12.000000      25  25.000000      2     1.0  1.00  27.753301  
74   3.000000     115  25.000000      1     1.0  0.67  49.787445  
75   3.000000     110  25.000000      1     1.0  1.00  51.592193  
76   8.000000      60  25.000000      1     1.0  0.75  36.187559  

[77 rows x 16 columns]

# One Hot Encoding

In [15]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder(categories='auto')

In [16]:
ohe=OneHotEncoder(sparse=False,categories='auto')
ohe.fit_transform(data)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
ohe.categories_

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1]),
 array([ 50,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160], dtype=int64),
 array([1, 2, 3, 4, 5, 6], dtype=int64),
 array([1.  , 1.56, 2.  , 3.  , 5.  ]),
 array([ 15.        ,  45.        ,  70.        ,  75.        ,
         80.        ,  90.        ,  95.        , 125.        ,
        130.        , 135.        , 140.        , 150.        ,
        160.        , 170.        , 180.        , 180.80882353,
        190.        , 200.        , 210.        , 220.        ,
        230.        , 240.        , 250.        , 260.        ,
        280.        , 290.        , 320.        ]),
 array([

In [18]:
x=data.iloc[:,0:15]
x

name  mfr  type  calories  protein   fat  sodium      fiber  carbo  \
0      0    3     0        70        4  1.00   130.0  10.000000    5.0   
1      1    5     0       120        3  5.00    15.0   2.000000    8.0   
2      2    2     0        70        4  1.00   260.0   9.000000    7.0   
3      3    2     0        50        4  1.56   140.0  14.000000    8.0   
4      4    6     0       110        2  2.00   200.0   1.000000   14.0   
..   ...  ...   ...       ...      ...   ...     ...        ...    ...   
72    72    1     0       110        2  1.00   250.0   2.856897   21.0   
73    73    1     0       110        1  1.00   140.0   2.856897   13.0   
74    74    6     0       100        3  1.00   230.0   3.000000   17.0   
75    75    1     0       100        3  1.00   200.0   3.000000   17.0   
76    76    1     0       110        2  1.00   200.0   1.000000   16.0   

       sugars  potass   vitamins  shelf  weight  cups  
0    6.000000     280  25.000000      3     1.0  0.33  
1    8.000000     135  31.521739      3     1.0  1.00  
2    5.000000     320  25.000000      3     1.0  0.33  
3    7.614286     330  25.000000      3     1.0  0.50  
4    8.000000      -1  25.000000      3     1.0  0.75  
..        ...     ...        ...    ...     ...   ...  
72   3.000000      60  25.000000      3     1.0  0.75  
73  12.000000      25  25.000000      2     1.0  1.00  
74   3.000000     115  25.000000      1     1.0  0.67  
75   3.000000     110  25.000000      1     1.0  1.00  
76   8.000000      60  25.000000      1     1.0  0.75  

[77 rows x 15 columns]

In [19]:
y=data.iloc[:,15].values
y

array([68.402973, 33.983679, 59.425505, 93.704912, 34.384843, 29.509541,
       33.174094, 37.038562, 49.120253, 53.313813, 18.042851, 50.764999,
       19.823573, 40.400208, 22.736446, 41.445019, 45.863324, 35.782791,
       22.396513, 40.448772, 64.533816, 46.895644, 36.176196, 44.330856,
       32.207582, 31.435973, 58.345141, 40.917047, 41.015492, 28.025765,
       35.252444, 23.804043, 52.076897, 53.371007, 45.811716, 21.871292,
       31.072217, 28.742414, 36.523683, 36.471512, 39.241114, 45.328074,
       26.734515, 54.850917, 37.136863, 34.139765, 30.313351, 40.105965,
       29.924285, 40.69232 , 59.642837, 30.450843, 37.840594, 41.50354 ,
       60.756112, 63.005645, 49.511874, 50.828392, 39.259197, 39.7034  ,
       55.333142, 41.998933, 40.560159, 68.235885, 74.472949, 72.801787,
       31.230054, 53.131324, 59.363993, 38.839746, 28.592785, 46.658844,
       39.106174, 27.753301, 49.787445, 51.592193, 36.187559])

In [20]:
x=oh.fit_transform(data).toarray()  
z=oh.fit_transform(x[:,1:2]).toarray()
x=np.delete(x,0,axis=1)          
x=np.concatenate((z,x),axis=1)

In [21]:
x

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

# Feature Scaling

In [22]:
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

# Splitting the dataset into Training set and Test set

In [23]:
from sklearn import model_selection, neighbors
from sklearn.model_selection import train_test_split,cross_val_score,cross_val_predict
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [24]:
y_train

array([59.425505, 28.025765, 22.396513, 72.801787, 40.917047, 50.828392,
       40.69232 , 32.207582, 38.839746, 34.139765, 55.333142, 34.384843,
       30.313351, 50.764999, 28.742414, 51.592193, 40.400208, 18.042851,
       52.076897, 53.313813, 64.533816, 29.924285, 58.345141, 59.363993,
       49.511874, 36.187559, 40.448772, 45.863324, 59.642837, 46.895644,
       29.509541, 63.005645, 33.174094, 68.402973, 19.823573, 44.330856,
       36.176196, 46.658844, 21.871292, 74.472949, 41.445019, 23.804043,
       40.560159, 40.105965, 41.015492, 39.106174, 45.328074, 30.450843,
       41.50354 , 41.998933, 37.840594, 36.471512, 31.435973])

In [25]:
x_test

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [26]:
y_test

array([27.753301, 54.850917, 22.736446, 45.811716, 37.136863, 53.131324,
       31.230054, 93.704912, 35.252444, 60.756112, 35.782791, 49.120253,
       53.371007, 26.734515, 39.259197, 39.241114, 49.787445, 28.592785,
       33.983679, 37.038562, 68.235885, 36.523683, 31.072217, 39.7034  ])

In [27]:
x_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])